package com.market.common.entity;

import java.io.Serializable;
import java.util.Date;

public class UserBasicBean implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_BASIC.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_BASIC.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_BASIC.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_BASIC.cellphone
     *
     * @mbg.generated
     */
    private Integer cellphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_BASIC.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_BASIC.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_BASIC.ct
     *
     * @mbg.generated
     */
    private Date ct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_BASIC.upt
     *
     * @mbg.generated
     */
    private Date upt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_USER_BASIC
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_BASIC.id
     *
     * @return the value of T_USER_BASIC.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_BASIC.id
     *
     * @param id the value for T_USER_BASIC.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_BASIC.name
     *
     * @return the value of T_USER_BASIC.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_BASIC.name
     *
     * @param name the value for T_USER_BASIC.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_BASIC.sex
     *
     * @return the value of T_USER_BASIC.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_BASIC.sex
     *
     * @param sex the value for T_USER_BASIC.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_BASIC.cellphone
     *
     * @return the value of T_USER_BASIC.cellphone
     *
     * @mbg.generated
     */
    public Integer getCellphone() {
        return cellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_BASIC.cellphone
     *
     * @param cellphone the value for T_USER_BASIC.cellphone
     *
     * @mbg.generated
     */
    public void setCellphone(Integer cellphone) {
        this.cellphone = cellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_BASIC.password
     *
     * @return the value of T_USER_BASIC.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_BASIC.password
     *
     * @param password the value for T_USER_BASIC.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_BASIC.status
     *
     * @return the value of T_USER_BASIC.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_BASIC.status
     *
     * @param status the value for T_USER_BASIC.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_BASIC.ct
     *
     * @return the value of T_USER_BASIC.ct
     *
     * @mbg.generated
     */
    public Date getCt() {
        return ct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_BASIC.ct
     *
     * @param ct the value for T_USER_BASIC.ct
     *
     * @mbg.generated
     */
    public void setCt(Date ct) {
        this.ct = ct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_BASIC.upt
     *
     * @return the value of T_USER_BASIC.upt
     *
     * @mbg.generated
     */
    public Date getUpt() {
        return upt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_BASIC.upt
     *
     * @param upt the value for T_USER_BASIC.upt
     *
     * @mbg.generated
     */
    public void setUpt(Date upt) {
        this.upt = upt;
    }
}