package com.market.common.mapper;

import com.market.common.entity.UserBasicBean;

public interface UserBasicBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_BASIC
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_BASIC
     *
     * @mbg.generated
     */
    int insert(UserBasicBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_BASIC
     *
     * @mbg.generated
     */
    int insertSelective(UserBasicBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_BASIC
     *
     * @mbg.generated
     */
    UserBasicBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_BASIC
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserBasicBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_BASIC
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserBasicBean record);
}